### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/x64asm#140]
We've classically had the problem of not being comparable to the GNU toolchain because there are multiple ways to emit valid assembly for a given instruction.  So how about testing like this:

Use stoke search to randomly pick an instruction
Generate a random initial state for the CPU
Use stoke's sandbox to run the instruction on the initial state
Use stoke's sandbox again, but use hex emitted by gas for the instruction
Diff the resulting CpuStates

This might help uncover remaining bugs in the assembler/sandbox.

**Comment by eschkufz** [comment]
Sounds good to me. I'd bubble the testing up into stoke though so we don't
get a circular dependency between the repositories.

On Mon, Feb 2, 2015 at 2:29 PM, Berkeley Churchill <notifications@github.com

**Comment by bchurchill** [comment]
Yeah, for sure.  There are some x64asm tests already in stoke which we
could add to.

**Comment by eschkufz** [comment]
Sounds good to me.

On Mon, Feb 2, 2015 at 2:36 PM, Berkeley Churchill <notifications@github.com

**Comment by rknath** [comment]
Since not all the instructions are implemented, it would be nice for users like me to have a fuzz test that checks only a given set of instructions. The make test interface takes quite a while. That will allow users like me more comfortable with implementing new instructions and contributing to stoke

**Comment by bchurchill** [comment]
The current 'make test' is also buggy and produces nearly all
false-positives.  It's not recommended at all.  The only thing that's
good about it, is that if it says something is correct, then it's
actually correct (because it matches gnu's assembler).

**Comment by rknath** [comment]
@bchurchill 
do you have any current known list of instructions which have wrong entries in the spread sheet?

**Comment by bchurchill** [comment]
Nope.  We usually fix these pretty quickly -- this psllw we've postponed
since it requires touching more code and we've been busy.  Any that we
know about go on the tracker.  The instructions that we have circuits
for are very unlikely to be wrong because they go through the fuzz tester.

**Comment by eschkufz** [comment]
This issue seems closed to me. Reopen if I'm wrong.

**Comment by bchurchill** [comment]
We have no testing infrastructure for x64asm that's not replete with false positives.

**Comment by eschkufz** [comment]
I thought the consensus was that this issue was being moved to stoke.

**Comment by bchurchill** [comment]
Well, the problem is in x64asm and the implementation will be in stoke
(if I implement it as described).  I just don't want to loose track of
it but don't care where the ticket is.  You can move it if you like.

**Comment by eschkufz** [comment]
Whatev. Here is fine.
