### ISSUE TITLE
Do we have something like Instruction.can_raise_exception()?

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/x64asm#151]
I'd like to know if an instruction can potentially raise an "exception" (not sure what the technically correct term is here), such as div-by-0, or segfault for memory reads/writes, etc.

Background:  When I try to remove redundant instructions after a STOKE search, we shouldn't remove anything that might have visible side-effects like raising an exception.

**Comment by eschkufz** [comment]
Ooof. Not really.

The short answer is that anything implicitly or explicitly dereferences
memory can raise sigsegv and any of the div instructions can raise sigfpe.
Also anything that Sandbox::is_unsupported() returns true for can raise
sigill. UD2 can raise sigill too.

**Comment by stefanheule** [comment]
Ok, that all makes sense.  Some floating point operations can also raise exceptions, no?

Do you think it would make sense to implement something like this here, or should I just have a helper method in my code (in STOKE)?

**Comment by bchurchill** [comment]
Stefan and I talked about this some earlier.   I tend to think that if
we implement this in terms of the hardware (i.e. what hardware
exceptions an instruction can cause) it should go in x64asm; but if we
implement this in terms of the sandbox signals it should go in stoke. 
What do you all think?

**Comment by eschkufz** [comment]
Agreed. If it relates to the implementation of the sandbox I would put it
in stoke.

**Comment by eschkufz** [comment]
I'd make it a static member of the sandbox just like is_unsupported().

**Comment by stefanheule** [comment]
That makes sense, but I don't think it does need to relate to the sandbox.  It would just be about whether the instruction can raise a hardware exception.  And we could still have a static method in the sandbox that returns true in the same cases, plus whenever the sandbox signals (e.g. unsupported things).  Does that make sense?

**Comment by bchurchill** [comment]
Yeah, that makes sense.  We should be sure to distinguish between types
of hardware instructions in the x64asm api though.  Behold the coming of
"ExceptionSet", "ExceptionSetReader", "ExceptionSetWriter".

**Comment by eschkufz** [comment]
If it relates to the actual behavior of the instruction when executed
directly on the hardware, then I think it should go in x64asm.

**Comment by eschkufz** [comment]
If you want to go that route, it should really be added to the spreadsheet
and everything.

**Comment by stefanheule** [comment]
Ok, thanks for all the input.  I looked at the manual a bit, and I think to do this properly here would be a lot of work, so for now I'll add a small helper to STOKE that covers what I need.

**Comment by eschkufz** [comment]
Sorry for the lag. Yeah. That sounds good to me. I'm perfectly happy yo
have extended error codes beginning from 256 that describe stoke specific
error modes.
