### ISSUE TITLE
Add some new iterators to reg set

### ISSUE THREAD

**Issue by eschkufz** [StanfordPL/x64asm#153]
I'd like to have iterators that will tell me the sse registers with any elements set and the gp registers with any elements set.

It's fine for me to get ymm0, ymm1, ymm2, etc.... instead of xmm0, ymm1, xmm2, etc...

**Comment by bchurchill** [comment]
Could you explain what these do?  Does this iterate over _every_ gp/sse register that's in the regset, not just the biggest one?  I think that's what I want but I can't tell.  I'm happy to update the comments in the source.

**Comment by eschkufz** [comment]
These iterate over 64-bit registers / 256-bit sse registers that have ANY
of their subregisters set.

So if your set contains ax, rdi, esi / xmm0 ymm1, the iterators gives you
-- rax, rdi, rsi / ymm0, ymm1
