### ISSUE TITLE
Invalid spreadsheet entries for read/write sets for many instructions

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/x64asm#159]
The maybe_read_set of movsd is wrong.  For `movsd %xmm12, %xmm8`, it is reported as `{ %xmm12 }`, but it should be `{ %xmm8, %xmm12 }`.  This is because `movsd` leaves the upper 64 bits of `%xmm8` unchanged.

I looked at the spreadsheet, and I think the Properties column reads "W, R", which looks right to me (but every time I look at the spreadsheet, I don't understand what most things mean.  If anybody explains this to me (again?), I will write it down in a README or something).  So, I don't know why this is happening.

I also wonder if there are other opcodes with the same problem (like `movss`, etc.)?

**Comment by eschkufz** [comment]
You probably want to change the properties column to RW, R. There are
probably some other instructions that exhibit this behavior and would need
to be changed as well. When we originally wrote this code, we didn't know
or want to think about the fact that you could write unnameable
subregisters of %xmmN.

**Comment by stefanheule** [comment]
Yes, "RW, R" is what I need, I also just realized this.  This kind of information is important to be accurate if the dataflow analysis should be accurate.  For the postprocessing, for instance, this is crucial.  I'll fix this.

**Comment by stefanheule** [comment]
The new fuzz tester I build found many more spreadsheet bugs, and I'll use ticket to fix all of them.  So far, at least the following instructions have invalid spreadsheet entries:
- movhlps
- movhpd
- movhps
- movlhps
- movlpd
- movlps
- movsd
- movss
- rclb
- rcll
- rclq
- rclw
- rcpss
- rcrb
- rcrl
- rcrq
- rcrw
- rsqrtss
- sqrtsd
- sqrtss

**Comment by stefanheule** [comment]
Question: For movss/movsd, the destination can be either xmm or memory.  In the former case, the destination is read (because the upper bits are left unchanged), but not in the memory case.  In the spreadsheet, there is only a single row, so (to be conservative), the memory destination is now also in the maybe_read_set.  Is that a problem?  Can I fix that?  Here is the relevant row (after my change):

```
F3 0F 11 /r MOVSS xmm2/m32, xmm MR  RW, R                       V   V   SSE movss       Move scalar single-precision floating-point value from xmm1 register to xmm2/m32.
```

**Comment by eschkufz** [comment]
Is that relevant? Yes.
Can you fix that? No without rewriting everything.

**Comment by stefanheule** [comment]
Actually, it seems that I could fix it with rather minimal effort by
introducing a new letter (like R, W or Z) that basically means R for
register operands and means nothing for memory operands. Is that right? I
don't know this part particularly well.
And if it is correct, us this something we want. Or would it add too much
complexity?

**Comment by stefanheule** [comment]
I just tried this, and it works.  I think this tiny 2 line-change is worth the additional precision.

**Comment by eschkufz** [comment]
Sounds good. Just document it somewhere.

**Comment by stefanheule** [comment]
Do we have any place to do that?  I don't think any of the other cases are documented (other than in the code of Codegen.hs).

**Comment by eschkufz** [comment]
We should probably add a new file that documents that contents of the
spreadsheet.

**Comment by stefanheule** [comment]
That seems like a good idea, but I'm probably not the right person to do that (I don't really understand all of the things in the spreadsheet, and how exactly they work). :/

**Comment by eschkufz** [comment]
Just make a ticket then and explain what you just did. We'll get to it
eventually.
