### ISSUE TITLE
Documentation for the spreadsheet

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/x64asm#160]
We should have some documentation for what the spreadsheet format is.  This should include the improvements made in #159.

**Comment by bchurchill** [comment]
In general, I like the idea of using github's resources for knowledge management.  So far, that's mostly been README.md files and using the issue tracker (e.g. things marked 'question').  One thing we haven't been using is the wiki.  I'm somewhat disinclined to have too many tools for such a purpose, so howabout a SPREADSHEET.md file inside the src directory?

**Comment by eschkufz** [comment]
Sounds good to me.

**Comment by stefanheule** [comment]
Yeah, I like that much better than a wiki, too.  This way we have all the information in one place (the repository)!
