### ISSUE TITLE
MISSING RETURN STATEMENTS IN IS_AVX AND IS_AVX2

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/x64asm#165]
This is likely causing all of our woes.

I was suspecting a value wasn't being initialized right, so I started turning on more compiler warnings and found these.  This fix will include substantially meaner options for g++.

**Comment by stefanheule** [comment]
Thank you, you are my hero!

**Comment by bchurchill** [comment]
Closed in 4279d51

**Comment by eschkufz** [comment]
Amazing!!!
