### ISSUE TITLE
vinsertps failed fuzz tester

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/x64asm#166]
SpreadsheetReadWriteSetFuzzTest Failed!

Instruction: vinsertps $0x7, %xmm12, %xmm1, %xmm15
  Maybe read set: { %xmm12 }
  Must write set: { %xmm1 %ymm15 }

Bits 0..64 of %xmm1 differ.
  In state 1: 0x5dfc36cc57d59496
  In state 2: 0x759355e339057b68
Bits 64..128 of %xmm1 differ.
  In state 1: 0xa4eb2f04ac461444
  In state 2: 0x9679fc4f7f8012f8
Bits 64..128 of %ymm15 differ.
  In state 1: 0xa4eb2f0400000000
  In state 2: 0x9679fc4f00000000

State 1:

SIGNAL 0 [normal exit]

[ 1 symbols ]

00000000 00400000 silly

%rax     13 9f f4 36 2d c0 83 12
%rcx     65 70 c3 1b cd 4c 22 4b
%rdx     30 8a 72 ae 34 1a 5d 97
%rbx     20 65 57 0e 7f db 95 1f
%rsp     00 00 00 07 00 00 00 00
%rbp     cb 8f a3 33 2a 32 70 0f
%rsi     3a df 8a 1b af ff a9 00
%rdi     eb 4d 1f 11 2d ba ba 1f
%r8      96 c5 21 87 5f fc 9a 45
%r9      9b 90 4f 9a c5 c0 f7 91
%r10     38 4e 29 19 14 4a 8f f8
%r11     6d df b2 28 f4 65 08 e3
%r12     8e 6a 92 fd d4 cd dc 4d
%r13     71 bf e3 79 24 53 2a 89
%r14     15 c5 d4 32 8c 85 09 73
%r15     2a 72 e8 dd 04 09 2a dc

%ymm0    43 7d 29 7f 53 b7 96 76 b2 8d 4b d6 78 86 02 46 fa 7c 3d 87 0b 7e a3 92 5a 50 68 d1 c1 fe 3f c4
%ymm1    cf f5 91 67 b1 14 3e 32 c1 87 9c 4b d4 0e 00 fe 96 79 fc 4f 7f 80 12 f8 75 93 55 e3 39 05 7b 68
%ymm2    00 af 16 f3 e0 21 62 79 70 4d 3b 3d 8c b4 a1 40 df 93 40 e1 fd c7 e4 ad 47 64 9b 4f ef 08 fa 0c
%ymm3    27 1e f0 17 1e 41 00 2a 61 df c8 e8 6f 7b ad 31 ef f9 90 ae 19 fd 6e 38 00 a7 54 52 5f ef b7 10
%ymm4    7a 45 e3 d3 1d c5 e3 06 a7 a2 06 7d 41 27 b4 59 b8 39 ac 86 4a b3 f6 9c 9a f9 2e 61 f9 87 0d a7
%ymm5    8d bb 38 9c 41 f3 b8 6d d6 f3 8a cf 4b e7 c9 ce a6 a2 1a 4c ea e0 a0 64 96 ec 6d fa 52 74 cc f1
%ymm6    2d 7d 3a 29 f0 7e f0 54 3d fd 9c d0 27 a9 46 57 5d 5e 8e 8f b8 eb 75 6c 01 94 cc 9d fe df 2f 04
%ymm7    21 43 29 b8 16 ac 7e ed bb ff fc 67 c2 ff cb f2 d8 22 ac 81 c4 4d f3 35 95 07 c0 29 06 2c 5d 69
%ymm8    95 49 be 0f 27 7b e5 6f 65 39 f1 78 7e f2 7b 17 30 7c 4c 3e a3 2a 92 22 65 44 2f 30 af 28 6f 86
%ymm9    a2 92 4d 74 fc 04 b6 ed dc 3b 08 6d d6 ce 7b 5e 50 89 e2 39 59 66 ed 1b c3 c3 89 a0 5e 45 71 2e
%ymm10   33 a6 8e 75 04 fc 28 8f ff 24 d9 12 47 9e 0a da c8 3b 5f 6a eb d5 88 b1 7c 21 c4 60 5e 00 d7 be
%ymm11   4d 8c 20 e8 59 79 5a e4 75 5e bc e6 5f 98 0c 4d 50 6e 43 76 a5 07 17 3b 1c 41 b3 6b c5 91 a7 65
%ymm12   e7 34 4f 20 e6 c3 00 fe 6a 87 a3 86 11 45 ca 2b e6 32 1f 99 e1 b1 56 6b 0b 4e 54 d0 32 13 1d c7
%ymm13   53 e5 3e e6 fd 0a 97 dd 23 d4 dc 25 6a 55 82 e4 44 3d 1a 18 57 e8 f9 be 07 48 68 9b 3d 19 47 6c
%ymm14   50 1f 20 cb cc 3b 8d e5 3d 83 4e 60 60 79 84 3a 0f 2e b8 2a ea 7b 10 d2 24 27 d8 66 20 90 fe 85
%ymm15   0e a5 7a ef 54 5b cf 89 8f 94 fb a9 57 78 5b f6 18 e2 72 dd d3 44 25 a8 59 a9 98 87 85 71 af 1e

%cf      1 
%1       1 
%pf      0 
%0       0 
%af      1 
%0       0 
%zf      0 
%sf      0 
%tf      0 
%if      1 
%df      0 
%of      0 
%iopl[0] 0 
%iopl[1] 0 
%nt      0 
%0       0 
%rf      0 
%vm      0 
%ac      0 
%vif     0 
%vip     0 
%id      0 

[ 00000007 00000000 - 00000006 ffffffe0 ]
[ 4 valid rows shown ]

00000006 fffffff8   v v v v v v v v   58 3f 11 4e 02 63 9e 6f 
00000006 fffffff0   v v v v v v v v   4d 75 61 a8 fb 72 53 a0 
00000006 ffffffe8   v v v v v v v v   a2 ca 11 0e cf 67 b7 57 
00000006 ffffffe0   v v v v v v v v   0c c0 3f 2a 4e 61 57 0a 

[ 00000001 00000000 - 00000001 00000000 ]
[ 0 valid rows shown ]

[ 00000000 00000000 - 00000000 00000000 ]
[ 0 valid rows shown ]

State 2:

SIGNAL 0 [normal exit]

[ 1 symbols ]

00000000 00400000 silly

%rax     36 9e 67 df 92 a6 a0 68
%rcx     b7 ce d0 17 2c 05 06 1e
%rdx     11 18 27 a2 cb b2 40 23
%rbx     f5 6c 53 8d 13 14 7b c5
%rsp     00 00 00 07 00 00 00 00
%rbp     02 fa 92 df 43 c3 0f 2c
%rsi     98 86 e6 d3 74 ce ac d2
%rdi     e0 e4 18 ed ef ac 9a 62
%r8      bf 3b bd 93 a4 b3 6c 2a
%r9      63 ad fd 91 ab 03 ff cc
%r10     c4 16 5e 62 7d d8 7b aa
%r11     04 c5 97 da e5 b3 c2 f8
%r12     02 56 e4 36 97 a8 79 04
%r13     01 d7 5a 57 74 ad 59 e3
%r14     05 fc 94 0d 38 7e af d6
%r15     4a 35 b0 46 30 ea af 56

%ymm0    76 b2 b8 4d 68 83 9d 21 53 b2 72 fc ad 76 68 9f 3e e9 f0 68 e8 18 0e 91 a4 61 38 c1 5f e1 dd 29
%ymm1    b9 63 10 23 ed 5d 6a a0 f5 e7 03 d4 94 51 61 97 a4 eb 2f 04 ac 46 14 44 5d fc 36 cc 57 d5 94 96
%ymm2    86 9c 0f e2 e3 ac d2 c0 be 75 55 1e 7f 6e 1a ab da c9 4a 43 25 5f 13 21 b2 cd 0c 6e 70 10 38 a4
%ymm3    c3 ed f8 7b 67 5c 6c 84 79 c0 b2 b9 01 3d 63 e3 bd f5 c9 12 1a ff c8 d7 da 69 c4 b9 b6 f6 ac 48
%ymm4    1d 50 42 78 8c 55 80 11 ee 24 a5 69 ab e5 b7 f2 e3 7a 8f 00 bd 9a 37 ab 7f 37 e3 a8 5d 7a e4 a4
%ymm5    5c 4f 44 36 32 f4 f3 ba 67 9e 39 56 b0 15 b1 47 69 cc 8f 77 e9 15 e8 e9 58 4e b2 ad ce 7a ca 26
%ymm6    d0 d3 cc c2 77 7c 7e 41 4a 8a 4d 90 22 af 56 cc fe 41 1a b7 d8 4e 28 61 65 13 79 7c bb 2b ca 0e
%ymm7    01 68 04 6b 98 30 9f d6 b9 22 58 78 d8 ce 2b 48 ab 7c f2 df 7d b0 c5 c6 d8 77 9e 77 12 8b fe 96
%ymm8    e4 43 d6 e2 42 6e de d7 d6 ad 38 00 f4 16 a8 7b 3d da 50 f5 2e d4 03 4f 57 52 8a 91 7a 13 f3 02
%ymm9    c3 97 92 fa b3 4f 24 d1 0c b6 f3 35 e0 45 fc e0 51 e6 38 d6 a9 5e 85 b4 2f b1 b1 e0 5a 5e 56 c9
%ymm10   f3 e6 cf 0a 23 37 77 29 84 28 05 b3 1c 4f c0 e7 6f 7b ea 8f 29 04 57 53 5b f9 ce a7 c9 1d f6 e9
%ymm11   8d 55 90 c8 62 aa f9 58 87 c1 e1 5e 3d b8 59 89 9c 0a c9 b5 9b 4e cb 0c 24 c7 b5 d1 6c bc 03 c5
%ymm12   e7 34 4f 20 e6 c3 00 fe 6a 87 a3 86 11 45 ca 2b e6 32 1f 99 e1 b1 56 6b 0b 4e 54 d0 32 13 1d c7
%ymm13   04 bd 24 6b 35 ae e4 41 c5 b2 dd a4 e3 23 7c 6d f1 16 d7 1e ec fa a4 4c ba 34 75 2f 60 ec 6f 99
%ymm14   bb a4 81 28 a0 c3 03 35 8e 55 51 4d 8f 9f 70 eb bb 4c 6e 4e 5b 58 77 3d 6c 7c 99 1f c2 64 aa 93
%ymm15   41 34 e6 16 78 42 95 50 a1 d1 4d 6c 43 f8 1a f6 68 7b 86 7d c0 3a 0f 71 df b6 fa a2 4a 7e 09 2b

%cf      1 
%1       1 
%pf      0 
%0       0 
%af      1 
%0       0 
%zf      1 
%sf      0 
%tf      0 
%if      1 
%df      0 
%of      0 
%iopl[0] 0 
%iopl[1] 0 
%nt      0 
%0       0 
%rf      0 
%vm      0 
%ac      0 
%vif     0 
%vip     0 
%id      0 

[ 00000007 00000000 - 00000006 ffffffe0 ]
[ 4 valid rows shown ]

00000006 fffffff8   v v v v v v v v   58 3f 11 4e 02 63 9e 6f 
00000006 fffffff0   v v v v v v v v   4d 75 61 a8 fb 72 53 a0 
00000006 ffffffe8   v v v v v v v v   a2 ca 11 0e cf 67 b7 57 
00000006 ffffffe0   v v v v v v v v   0c c0 3f 2a 4e 61 57 0a 

[ 00000001 00000000 - 00000001 00000000 ]
[ 0 valid rows shown ]

[ 00000000 00000000 - 00000000 00000000 ]
[ 0 valid rows shown ]

././tests/x64asm/read_write_sets.h:45: Failure
Failed

**Comment by stefanheule** [comment]
I can take this.
