### ISSUE TITLE
static map members of Label have undefined interaction with static data structures

### ISSUE THREAD

**Issue by eschkufz** [StanfordPL/x64asm#168]
C doesn't guarantee an initialization order on static data structures. This causes Label's static maps to behave strangely when used as part of other static initialization code.

Specifically, see trying to create Code in a default constructor that is used as part of a cpputil arg.

**Comment by eschkufz** [comment]
Solve this by wrapping static members in static members and deferring initialization to first function call. Singleton. Classic.

**Comment by bchurchill** [comment]
At some point could you explain why the behavior was undefined to me? 
This seems like one of those C++ things I'm not familiar with.

**Comment by eschkufz** [comment]
C doesn't guarantee an initialization order among static variables in
different translation units. So this code is undefined --

// a.h
class X {
 static std::map<int,int> m; // m is defined
}

// a.cc
std::map<int,int> X::m // m is declared

// b.cc
#include "a.h"
int global = X::m[0] // m is dereferenced

You can't guarantee that m has been declared / initialized when static
storage and initial values for global are computed.

The reason this was a bug was because the cpputils arg library does a ton
of stuff with static variables and it was having a strange interaction with
the static maps inside the label class.

The solution is something like this --

// a.h
class X {
  static std::map<int,int>& m() {
    static std::map<int,int> m; // m is defined and declared
    return m;
  }
}

// a.cc
// nothing here now

// b.cc
#include "a.h"
int global = X::m()[0] // m is dereferenced

The semantics are identical, but the initialization code that the compiler
emits is forced into a function which imposes an ordering on the evaluation
of the dereference in the assignment to global. The map has to be
initialized before the index takes place.

**Comment by eschkufz** [comment]
This is the singleton design pattern.

You can take a look at cpputil::Singleton<T> for an example. It's basically
a templated version of this concept.

**Comment by bchurchill** [comment]
Cool, thanks!

Berkeley

**Comment by eschkufz** [comment]
Manolis could probably talk your ear off about this all day.
