### ISSUE TITLE
Auto-generate latency tables for user's hardware

### ISSUE THREAD

**Issue by eschkufz** [StanfordPL/x64asm#176]
This is something stoke needs which is pretty easy to automatically generate at this point. The alternate is to keep track of this data by hand, which is pretty mind-numbing.

**Comment by bchurchill** [comment]
This seems really, really hard to me.  Why do you say it's easy?  Maybe
I'm missing something.

**Comment by eschkufz** [comment]
At least to the same standard of quality as we have now.

All you need is a program that iterates over every instruction, assembles
it into a function, calls that function a bajillion times and averages the
runtime. If we ignore instructions that take memory (which our current
table does anyway), generating sensible operands is pretty easy.

I'm pretty much done with this. Just testing before I check it in.

On Mon, Apr 6, 2015 at 4:15 PM, Berkeley Churchill <notifications@github.com

**Comment by eschkufz** [comment]
I'm doing something slightly fancier than that.

I'm also measuring the time it takes to run an empty function a bajillion
times and counting the difference to eliminate the overhead of calling a
function from the estimate.

**Comment by bchurchill** [comment]
Alright.  I'd be interested to see the results and how it compares to
our tables.  Also, I think it would be interesting to do the measurement
in a few different ways: perhaps with/without the function call, and
perhaps also try running the instruction multiple times in a loop.  It
would be nice to see if this gives noticeably different results for some
instructions.

I worry that for some instructions, having them all in a row would be a
pathological case compared to their normal use, and might end up doing
massive pipeline stalls.

**Comment by eschkufz** [comment]
They're _roughly_ the same. All of the stoke regression tests are passing
using the auto-generated tables, so they're at the very least not
pathologically different.

I think a little more work on this will get us something pretty good. We
might even be able to come up with much more sensible values for memory
accesses.

On Mon, Apr 6, 2015 at 4:51 PM, Berkeley Churchill <notifications@github.com

> wrote:
> 
> Alright. I'd be interested to see the results and how it compares to
> our tables. Also, I think it would be interesting to do the measurement
> in a few different ways: perhaps with/without the function call, and
> perhaps also try running the instruction multiple times in a loop. It
> would be nice to see if this gives noticeably different results for some
> instructions.
> 
> I worry that for some instructions, having them all in a row would be a
> pathological case compared to their normal use, and might end up doing
> massive pipeline stalls.
> 
> On 04/06/2015 04:19 PM, eric schkufza wrote:
> 
> > I'm doing something slightly fancier than that.
> > 
> > I'm also measuring the time it takes to run an empty function a bajillion
> > times and counting the difference to eliminate the overhead of calling a
> > function from the estimate.
> > 
> > On Mon, Apr 6, 2015 at 4:18 PM, eric schkufza eric.schkufza@gmail.com
> > wrote:
> > 
> > > At least to the same standard of quality as we have now.
> > > 
> > > All you need is a program that iterates over every instruction,
> > > assembles
> > > it into a function, calls that function a bajillion times and
> > > averages the
> > > runtime. If we ignore instructions that take memory (which our current
> > > table does anyway), generating sensible operands is pretty easy.
> > > 
> > > I'm pretty much done with this. Just testing before I check it in.
> > > 
> > > On Mon, Apr 6, 2015 at 4:15 PM, Berkeley Churchill <
