### ISSUE TITLE
Invalid opcodes: MOVSX_R64_RH and MOVZX_R64_RH

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/x64asm#177]
It seems we are generating a few invalid opcodes, like MOVSX_R64_RH.  This instruction is illegal, no matter what the operands are (because it takes a 64-bit argument and thus requires the REX prefix, but it also takes an RH argument, and thus cannot have an REX prefix).  Only two instructions are affected.

**Comment by eschkufz** [comment]
We can make a final pass to Codegen.hs that deletes any instructions like
these that are invalid.
