### ISSUE TITLE
MOV AL and REX prefix

### ISSUE THREAD

**Issue by avikivity** [StanfordPL/x64asm#209]
Your README states: "The Intel manual is unclear on what adding the REX.w+ prefix to MOV [mem8] AL accomplishes, but we support this behavior nonetheless."

The REX prefix is used to select from the register set AL/BL/CL/DL/SIL/DIL...R15L compared to the default of AL/AH...DL/DH.

**Comment by stefanheule** [comment]
Hey.  Thanks, we are aware of what the REX prefix normally is used for.  However, the statement in the README is about the particular MOV variant for the AL register.  There is no choice between register sets in this case, which is why the README points this out.
