### ISSUE TITLE
HLE/RTM instructions need to be marked as invalid

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/x64asm#229]
I'm pretty sure we can't handle any of these, so we should turn off x64asm support for these.

**Comment by stefanheule** [comment]
What exactly is "x64asm support"?  Wouldn't we mark them as unsupported in the sandbox?

**Comment by bchurchill** [comment]
There's a column in the spreadsheet that basically means "actually, we should never assemble this".

**Comment by bchurchill** [comment]
That entry prevents the instruction from being compiled into x64asm at all.

**Comment by stefanheule** [comment]
Ah, ok.  Either is fine with me.

**Comment by bchurchill** [comment]
I'm realizing that there's really no need to do this given the other fix to STOKE to use only whitelisted CpuFlags.  I guess these instructions might be useful to _someone_, _someday_, so I'll leave them.
