### ISSUE TITLE
Alternate instruction encodings are not supported

### ISSUE THREAD

**Issue by joeleong** [StanfordPL/x64asm#239]
failing to encode alternate instruction encodings, for example:
```asm
xorl.s %r9d, %r9d ; 45 33 c9
```

more examples:
https://github.com/facebookexperimental/binutils/blob/master/gas/testsuite/gas/i386/ilp32/x86-64-opts-intel.d 

see the direction bit here: 
http://www.c-jump.com/CIS77/CPU/x86/lecture.html#X77_0050_add_opcode

thanks to stoke-developers for helping me track it down and providing the links above

**Comment by stefanheule** [comment]
We fixed this in #240.
